# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjCSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjCSampleApp
  pod 'Map4dMap'
  pod 'Map4dMapUtils'

end
